#spring:
#  application:
#    name: nacos-service
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 118.190.217.50:8848
#        namespace: public
#        username: nacos
#        password: nacos
#
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#      eager: true
#
#
#server:
#  port: 8110
#
#
#mybatis:
#  mapper-locations: classpath:mappers/*xml
#  type-aliases-package: com.sxc.ojbackendmicroservice.mybatis.entity